spring:
  # H2
  h2.console:
    enabled: true
    path: /h2
    settings.web-allow-others: true
    settings.forbid-creation: false
  # Datasource
  datasource:
    url: jdbc:h2:mem:phoenixtestdb
    username: usr
    password: pwd
    driverClassName: org.h2.Driver
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: false
  # Swagger
  mvc.pathmatch.matching-strategy: ant_path_matcher

server:
  servlet:
    context-path: /phoenix
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

startup.question.count: 20

